#!/bin/bash

apt-get install apache2 php5 php5-cli php5-common php5-dev php5-gd php5-mcrypt php5-mysql php-pear php5-xmlrpc php5-memcache php-apc php-soap mysql-server mysql-client -y
chown -R www-data:www-data /var/www

